config/routes.rb
Rails.application.routes.draw do
  resources :topics

  resources :messageboards

root 'topics#index'

end

app/models/messageboard.rb
class Messageboard < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messageboards_controller.rb
class MessageboardsController < ApplicationController
  before_action :set_messageboard, only: [:show, :edit, :update, :destroy]

  # GET /messageboards
  # GET /messageboards.json
  def index
    @messageboards = Messageboard.all
  end

  # GET /messageboards/1
  # GET /messageboards/1.json
  def show
  end

  # GET /messageboards/new
  def new
    @messageboard = Messageboard.new
  end

  # GET /messageboards/1/edit
  def edit
  end

  # POST /messageboards
  # POST /messageboards.json
  def create
    @messageboard = Messageboard.new(messageboard_params)

    respond_to do |format|
      if @messageboard.save
        format.html { redirect_to @messageboard, notice: 'Messageboard was successfully created.' }
        format.json { render :show, status: :created, location: @messageboard }
      else
        format.html { render :new }
        format.json { render json: @messageboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messageboards/1
  # PATCH/PUT /messageboards/1.json
  def update
    respond_to do |format|
      if @messageboard.update(messageboard_params)
        format.html { redirect_to @messageboard, notice: 'Messageboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @messageboard }
      else
        format.html { render :edit }
        format.json { render json: @messageboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messageboards/1
  # DELETE /messageboards/1.json
  def destroy
    @messageboard.destroy
    respond_to do |format|
      format.html { redirect_to messageboards_url, notice: 'Messageboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_messageboard
      @messageboard = Messageboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def messageboard_params
      params.require(:messageboard).permit(:title, :description)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messageboards_helper.rb
module MessageboardsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Msgboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messageboards/_form.html.erb
<%= form_for(@messageboard) do |f| %>
  <% if @messageboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@messageboard.errors.count, "error") %> prohibited this messageboard from being saved:</h2>

      <ul>
      <% @messageboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messageboards/edit.html.erb
<h1>Editing Messageboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @messageboard %> |
<%= link_to 'Back', messageboards_path %>

app/views/messageboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messageboards</h1>

<table>
  <thead>
    <tr>
      <th>標題</th>
      <th>想說的話</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messageboards.each do |messageboard| %>
      <tr>
        <td><%= messageboard.title %></td>
        <td><%= messageboard.description %></td>
        <td><%= link_to 'Show', messageboard %></td>
        <td><%= link_to 'Edit', edit_messageboard_path(messageboard) %></td>
        <td><%= link_to 'Destroy', messageboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Messageboard', new_messageboard_path %>

app/views/messageboards/new.html.erb
<h1>New Messageboard</h1>

<%= render 'form' %>

<%= link_to 'Back', messageboards_path %>

app/views/messageboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @messageboard.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @messageboard.description %>
</p>

<%= link_to 'Edit', edit_messageboard_path(@messageboard) %> |
<%= link_to 'Back', messageboards_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>留言板(測試)</h1>

<table>
  <thead>
    <tr>
      <p><h3>輸入留言</h3></p>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New messages', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>